worker_processes  auto;

events {
    worker_connections  65536;
    use epoll;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile        on;

    keepalive_timeout  65;

    gzip                    on;
    gzip_min_length         1024;
    gzip_comp_level         5;
    gzip_buffers            8 16k;
    gzip_http_version       1.1;
    gzip_proxied            any;
    gzip_types              text/plain application/x-javascript application/javascript text/css application/xml text/javascript image/jpeg image/gif image/png;

    client_max_body_size    100m;
    client_body_buffer_size 10m;

    server {
        listen 80;
        server_name erp.huahui-in.com;
        set $api_gateway "192.168.0.9";

        # Redirect all HTTP requests to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name erp.huahui-in.com;
        set $api_gateway "192.168.0.9";     

        ssl_certificate /usr/local/nginx/conf/ssl/huahui-in.com/huahui-in.com.pem;
        ssl_certificate_key /usr/local/nginx/conf/ssl/huahui-in.com/huahui-in.com.key;

        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 5m;

        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;

        ssl_prefer_server_ciphers on;

        location / {
            root   /data/oms_web/html/;
            index  index.html;
            expires modified +30d;
            try_files $uri /oms/index.html;
            if ($request_filename ~* .*\.(?:htm|html)$) {
                add_header Cache-Control no-cache;
                add_header Pragma no-cache;
            }
        }
		

		location ^~ /ai-workbench {
			proxy_pass http://127.0.0.1:3001;

			proxy_http_version 1.1;

			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto https;
			proxy_set_header X-Forwarded-Host $host;

			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			proxy_read_timeout 300s;
			proxy_send_timeout 300s;
			proxy_redirect off;
		}
        
		location /bitable-plugin/ {
				alias /data/bitable-plugin/;
				index index.html;
			}

        location ^~ /api/ {
            proxy_pass http://$api_gateway:8762$request_uri;
            proxy_set_header Host  $host;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For  $http_x_forwarded_for;
        }
		
		location ^~ /feishu-plugin/ {
			alias /data/feishuPlugin/html/;
			index index.html;
			try_files $uri $uri/ /index.html;

			expires modified +30d;
			add_header Cache-Control no-cache;
			add_header Pragma no-cache;
		}
    }
	
}
