USE asset_portal;

ALTER TABLE directories
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '目录主键',
  MODIFY COLUMN parent_id BIGINT UNSIGNED NULL COMMENT '上级目录主键，顶级目录为空',
  MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '目录名称',
  MODIFY COLUMN description VARCHAR(500) NULL COMMENT '目录说明',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序，数值越小越靠前',
  MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active 启用，inactive 停用',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '应用目录表，维护工作台中的多级分类目录';

ALTER TABLE asset_types
  MODIFY COLUMN code VARCHAR(50) NOT NULL COMMENT '应用类型编码',
  MODIFY COLUMN name VARCHAR(80) NOT NULL COMMENT '应用类型名称',
  MODIFY COLUMN description VARCHAR(300) NULL COMMENT '应用类型说明',
  MODIFY COLUMN color VARCHAR(30) NOT NULL DEFAULT 'green' COMMENT '类型展示颜色',
  MODIFY COLUMN icon VARCHAR(50) NULL COMMENT '类型图标标识',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序，数值越小越靠前',
  MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active 启用，inactive 停用',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '应用类型字典表，定义应用的分类与展示样式';

ALTER TABLE assets
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '应用主键',
  MODIFY COLUMN directory_id BIGINT UNSIGNED NOT NULL COMMENT '所属目录主键',
  MODIFY COLUMN type VARCHAR(50) NOT NULL COMMENT '应用类型编码，关联 asset_types.code',
  MODIFY COLUMN name VARCHAR(160) NOT NULL COMMENT '应用名称',
  MODIFY COLUMN description VARCHAR(800) NULL COMMENT '应用说明',
  MODIFY COLUMN owner_user_id INT NULL COMMENT '历史负责人 EIP 用户 ID，兼容旧数据',
  MODIFY COLUMN owner_workcode VARCHAR(100) NULL COMMENT '负责人 EIP 工号，关联 eip.sys_user.workcode',
  MODIFY COLUMN owner_name VARCHAR(80) NULL COMMENT '历史负责人名称，仅用于兼容旧数据',
  MODIFY COLUMN department_name VARCHAR(120) NULL COMMENT '历史负责部门名称，仅用于兼容旧数据',
  MODIFY COLUMN url VARCHAR(1000) NOT NULL COMMENT '应用访问链接',
  MODIFY COLUMN open_mode VARCHAR(20) NOT NULL DEFAULT 'new_tab' COMMENT '打开方式：current_tab 当前页，new_tab 新标签页',
  MODIFY COLUMN tags JSON NOT NULL COMMENT '应用标签 JSON 数组',
  MODIFY COLUMN click_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '累计访问次数',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序，数值越小越靠前',
  MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active 启用，inactive 停用',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '应用资产表，维护工作台中可访问的应用入口';

ALTER TABLE asset_departments
  MODIFY COLUMN asset_id BIGINT UNSIGNED NOT NULL COMMENT '应用主键，关联 assets.id',
  MODIFY COLUMN department_id VARCHAR(128) NOT NULL COMMENT 'EIP 部门 ID，关联 eip.departmentinfo.departmentid',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  COMMENT = '应用与 EIP 负责部门关联表，一个应用可关联多个部门';

ALTER TABLE asset_visit_logs
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '访问日志主键',
  MODIFY COLUMN asset_id BIGINT UNSIGNED NOT NULL COMMENT '被访问的应用主键',
  MODIFY COLUMN user_id INT NULL COMMENT '历史访问用户 EIP ID，兼容旧数据',
  MODIFY COLUMN user_workcode VARCHAR(100) NULL COMMENT '访问用户 EIP 工号',
  MODIFY COLUMN department_id VARCHAR(128) NULL COMMENT '访问用户所属 EIP 部门 ID',
  MODIFY COLUMN user_name VARCHAR(120) NULL COMMENT '访问用户名称快照',
  MODIFY COLUMN user_email VARCHAR(255) NULL COMMENT '访问用户邮箱快照',
  MODIFY COLUMN department_name VARCHAR(120) NULL COMMENT '访问用户部门名称快照',
  MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT '访问来源 IP 地址',
  MODIFY COLUMN user_agent VARCHAR(500) NULL COMMENT '访问终端 User-Agent',
  MODIFY COLUMN visited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '访问时间',
  COMMENT = '应用访问日志表，用于访问统计与审计';

ALTER TABLE asset_favorites
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '收藏记录主键',
  MODIFY COLUMN user_id BIGINT NULL COMMENT '历史收藏用户 ID，兼容旧数据',
  MODIFY COLUMN user_workcode VARCHAR(100) NULL COMMENT '收藏用户 EIP 工号',
  MODIFY COLUMN asset_id BIGINT NOT NULL COMMENT '被收藏的应用主键',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '收藏创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '收藏更新时间',
  COMMENT = '用户应用收藏关联表，记录用户收藏的工作台应用';

ALTER TABLE quick_service_groups
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '快捷服务分组主键',
  MODIFY COLUMN name VARCHAR(120) NOT NULL COMMENT '快捷服务分组名称',
  MODIFY COLUMN description VARCHAR(500) NULL COMMENT '快捷服务分组说明',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序，数值越小越靠前',
  MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active 启用，inactive 停用',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '快捷服务分组表，维护快捷服务卡片的展示分组';

ALTER TABLE quick_service_cards
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '快捷服务卡片主键',
  MODIFY COLUMN group_id BIGINT UNSIGNED NOT NULL COMMENT '所属快捷服务分组主键',
  MODIFY COLUMN name VARCHAR(160) NOT NULL COMMENT '快捷服务名称',
  MODIFY COLUMN description VARCHAR(800) NULL COMMENT '快捷服务说明',
  MODIFY COLUMN url VARCHAR(1000) NOT NULL COMMENT '快捷服务访问链接',
  MODIFY COLUMN open_mode VARCHAR(20) NOT NULL DEFAULT 'new_tab' COMMENT '打开方式：current_tab 当前页，new_tab 新标签页',
  MODIFY COLUMN icon VARCHAR(50) NULL COMMENT '卡片图标标识',
  MODIFY COLUMN color VARCHAR(30) NOT NULL DEFAULT 'blue' COMMENT '卡片展示颜色',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序，数值越小越靠前',
  MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active 启用，inactive 停用',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = '快捷服务卡片表，维护工作台首页快捷入口';
